
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://hleepage.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)



# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

#force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Lee Page"
title: "Lee Page"
description: "Website of Lee Page."
keywords: "page, lee"
# favicon: ""
404-img: "/img/labtocat.png"

################
# Header layout #
################

# black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/the_latest_blur.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: 5 # Set False for infinite loop, or set any number for finite loop.
type-speed: 30
start-delay: 200
delete-delay: 8000
lines: # You can add HTML Tags in the Text

  # - text: "Something clever goes here."



me-img: "/img/headshot_square.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ruby.png"
    date: "Oct. 2015 - Jan. 2016"
    description: "Back-End Engineering (12-Week Immersive) at The Iron Yard, Nashville"
  - image: "/img/timeline/coding.png"
    date: "Oct. 2014 - Sept. 2015"
    description: "Learning to code (Udacity, Treehouse, Codeschool, you name it)"
  - image: "/img/timeline/hourglass.png"
    date: "May 1995 - Oct 2014"
    description: "IT Consulting,  Medical Device Sales, Faux and Decorative Painting, Making Music."
  - image: "/img/timeline/graduation.png"
    date: "Sept. 1991 - May 1995"
    description: "BA Anthropolgy, magna cum laude, Vanderbilt University"
  - image: "/img/timeline/early_earth.jpg"
    date: "4.6 BYA - Sept. 1991"
    description: "The Earth forms and cools. A lot of stuff happens."


# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "hleepage@yahoo.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/hleepage"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'projects'
  # Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'


# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "blog"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
